table DashboardInfo
	lineageTag: 59b66f38-5a01-4046-a4e9-2457df8dd87d

	column Version
		dataType: int64
		formatString: 0
		lineageTag: 5d958bc9-d40d-461e-b1b3-514d58e2d959
		summarizeBy: sum
		sourceColumn: Version

		annotation SummarizationSetBy = Automatic

	column 'Last Refresh'
		dataType: dateTime
		formatString: Long Date
		lineageTag: bd7a2956-27d9-413f-8036-f86b755069f8
		summarizeBy: none
		sourceColumn: Last Refresh

		variation Variation
			isDefault
			relationship: 61f11eff-e9f9-4bd4-912a-7e019d631651
			defaultHierarchy: LocalDateTable_1e8a99d6-78b9-43a2-942a-ab1ada8d575d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Author
		dataType: string
		lineageTag: 4779f434-6387-427b-a684-1ba2b17d3001
		summarizeBy: none
		sourceColumn: Author

		annotation SummarizationSetBy = Automatic

	partition DashboardInfo = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMtQzUNJRMrTUNTTQNTIwMgVyHFMySzIVwpRiYwE=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Version = _t, #"Last Refresh" = _t, Author = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Version", Int64.Type}, {"Last Refresh", type date}, {"Author", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

